python indoor_scene_verification/indoorhack/tasks/plot_tsne.py -e netvlad
python indoor_scene_verification/indoorhack/tasks/plot_tsne.py -e innetvlad-v1-20
python indoor_scene_verification/indoorhack/tasks/plot_tsne.py -e innetvlad-v2-20
python indoor_scene_verification/indoorhack/tasks/plot_tsne.py -e innetvlad-v3-20
python indoor_scene_verification/indoorhack/tasks/plot_tsne.py -e innetvlad-v1-10
python indoor_scene_verification/indoorhack/tasks/plot_tsne.py -e innetvlad-v2-10
python indoor_scene_verification/indoorhack/tasks/plot_tsne.py -e innetvlad-v3-10
python indoor_scene_verification/indoorhack/tasks/plot_tsne.py -e innetvlad-v1-30
python indoor_scene_verification/indoorhack/tasks/plot_tsne.py -e innetvlad-v2-30
python indoor_scene_verification/indoorhack/tasks/plot_tsne.py -e innetvlad-v3-30
